# Generated by Django 4.0.3 on 2024-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default=250, max_length=100),
            preserve_default=False,
        ),
    ]
